from datetime import datetime
from typing import Literal, Optional, List, Dict, Annotated
from typing_extensions import TypedDict
from pydantic import BaseModel, Field

class CurlConfig(BaseModel):
    """Configuration schema for executing curl commands during bisection."""
    method: Literal["GET", "POST", "PUT", "DELETE", "PATCH"] = Field(
        description="HTTP method to use for the request"
    )
    url: str = Field(
        description="URL to send the request to"
    )
    headers: Dict[str, str] = Field(
        default_factory=dict,
        description="HTTP headers as key-value pairs"
    )
    body: Optional[str] = Field(
        default=None,
        description="Optional request body content"
    )
    expected_status: int = Field(
        default=200,
        description="Expected HTTP response status code"
    )
    expected_body_contains: Optional[str] = Field(
        default=None,
        description="Substring that the response body must contain to be considered good"
    )
    expected_headers: Dict[str, str] = Field(
        default_factory=dict,
        description="HTTP response headers that must match exactly or as substrings"
    )

    model_config = {
        "extra": "forbid"
    }

class OracleResult(BaseModel):
    """The result of executing the oracle test script at a specific commit."""
    commit_hash: str = Field(
        description="Git commit hash corresponding to this test run"
    )
    status_code: int = Field(
        description="HTTP status code received from the endpoint"
    )
    response_body: str = Field(
        description="Raw HTTP response body received from the endpoint"
    )
    response_headers: Dict[str, str] = Field(
        description="HTTP headers returned in the response"
    )
    verdict: Literal["good", "bad"] = Field(
        description="Oracle verdict of whether this commit is good or bad"
    )
    latency_ms: float = Field(
        description="Response latency in milliseconds"
    )

    model_config = {
        "extra": "forbid"
    }

class BisectResult(BaseModel):
    """The outcome of a git bisect run."""
    faulty_commit_hash: str = Field(
        description="Commit hash that introduced the regression"
    )
    faulty_commit_message: str = Field(
        description="Commit message of the faulty commit"
    )
    faulty_commit_author: str = Field(
        description="Author of the faulty commit"
    )
    faulty_commit_timestamp: datetime = Field(
        description="Timestamp of when the faulty commit was created"
    )
    diff: str = Field(
        description="Git diff of the faulty commit"
    )
    iterations: int = Field(
        description="Number of bisect iterations run"
    )
    oracle_results: List[OracleResult] = Field(
        description="List of oracle results collected during the bisect run"
    )

    model_config = {
        "extra": "forbid"
    }

class FileContext(BaseModel):
    """Code contents and metadata for a suspected file in the workspace."""
    path: str = Field(
        description="File path relative to repository root"
    )
    content: str = Field(
        description="Relevant content of the file"
    )
    relevance_score: float = Field(
        description="LLM-assigned relevance score between 0.0 and 1.0"
    )

    model_config = {
        "extra": "forbid"
    }

class RcaReport(BaseModel):
    """Structured Root Cause Analysis (RCA) report generated by the agent."""
    faulty_commit: str = Field(
        description="The regression-introducing commit hash"
    )
    author: str = Field(
        description="The author of the breaking commit"
    )
    timestamp: datetime = Field(
        description="The timestamp of the breaking commit"
    )
    commit_message: str = Field(
        description="Commit message of the breaking commit"
    )
    root_cause: str = Field(
        description="Detailed explanation of the root cause of the regression"
    )
    breaking_change_summary: str = Field(
        description="High-level summary of the breaking changes introduced"
    )
    transitive_path: List[str] = Field(
        description="List of import paths or call chain from test trigger to regression source"
    )
    files_analysed: List[str] = Field(
        description="List of files that were analysed during the RCA process"
    )
    confidence: Literal["HIGH", "MEDIUM", "LOW"] = Field(
        description="Confidence score of the RCA report"
    )
    confidence_reasoning: str = Field(
        description="Explanation for the assigned confidence score"
    )
    suggested_next_steps: str = Field(
        description="Suggested remediation steps or further investigation path"
    )

    model_config = {
        "extra": "forbid"
    }

class AgentEvent(BaseModel):
    """Event schema used for streaming progress update to stdout in NDJSON format."""
    event: Literal[
        "phase_start", "phase_complete",
        "node_start", "node_complete",
        "tool_call", "tool_result",
        "rca_ready", "error"
    ] = Field(
        description="Type of the agent event"
    )
    payload: Dict = Field(
        description="Arbitrary event payload details"
    )

    model_config = {
        "extra": "forbid"
    }

class AgentState(TypedDict):
    """State definition for the LangGraph agent orchestration."""
    bisect_result: Annotated[BisectResult, Field(description="Result of the git bisect process")]
    curl_config: Annotated[CurlConfig, Field(description="Curl configuration used for testing the endpoint")]
    curl_error_response: Annotated[Optional[OracleResult], Field(description="The OracleResult representing the error response, if any")]
    diff_analysis: Annotated[Optional[str], Field(description="Analysis description of the diff from bisect")]
    suspected_files: Annotated[List[str], Field(description="List of file paths suspected to be involved in the regression")]
    file_contexts: Annotated[List[FileContext], Field(description="Code contents and details of suspected files")]
    correlation: Annotated[Optional[str], Field(description="Identified correlation between the diff and failure symptoms")]
    confidence: Annotated[Optional[Literal["HIGH", "MEDIUM", "LOW"]], Field(description="Confidence rating of the current analysis")]
    import_fetch_count: Annotated[int, Field(description="Count of transitive imports retrieved")]
    rca_report: Annotated[Optional[RcaReport], Field(description="The finalized RCA report")]
    events: Annotated[List[AgentEvent], Field(description="List of events recorded during agent execution")]


class FileChange(BaseModel):
    """Represents a specific file modification to be applied."""
    path: str = Field(
        description="Relative path of file to modify within the repo"
    )
    original_content: str = Field(
        description="Full original file content before fix"
    )
    new_content: str = Field(
        description="Full replacement file content after fix applied"
    )
    change_summary: str = Field(
        description="One-line human-readable description of what changed"
    )

    model_config = {
        "extra": "forbid"
    }


class FixPlan(BaseModel):
    """The plan proposed by the agent to address the regression."""
    files_to_modify: List[str] = Field(
        description="Relative paths of files the fix will touch"
    )
    changes_per_file: Dict[str, str] = Field(
        description="path -> description of the intended change"
    )
    reasoning: str = Field(
        description="Why this fix addresses the root cause from the RCA"
    )
    estimated_risk: Literal["LOW", "MEDIUM", "HIGH"] = Field(
        description="Risk level of applying this fix"
    )

    model_config = {
        "extra": "forbid"
    }


from pydantic import StrictBool

class FixResult(BaseModel):
    """The result of applying and verifying a proposed fix."""
    branch_name: str = Field(
        description="Git branch created for this fix e.g. fix/bisect-a3f2c1d"
    )
    commit_hash: str = Field(
        description="Hash of the fix commit on the new branch"
    )
    files_modified: List[str] = Field(
        description="Actual files written to disk"
    )
    patch_diff: str = Field(
        description="Full git diff of the fix commit"
    )
    verification_passed: StrictBool = Field(
        description="Whether oracle curl passed after fix was applied"
    )
    verification_response: OracleResult = Field(
        description="Full oracle result from post-fix verification run"
    )

    model_config = {
        "extra": "forbid"
    }


class FixAgentState(TypedDict):
    """State definition for the LangGraph fix agent orchestration."""
    rca_report: Annotated[RcaReport, Field(description="The finalized RCA report")]
    bisect_result: Annotated[BisectResult, Field(description="Result of the git bisect process")]
    curl_config: Annotated[CurlConfig, Field(description="Curl configuration used for testing the endpoint")]
    repo_path: Annotated[str, Field(description="Path to target repository")]
    file_contexts: Annotated[List[FileContext], Field(description="Code contents and details of suspected files")]
    fix_plan: Annotated[Optional[FixPlan], Field(description="The generated plan to fix the regression")]
    file_changes: Annotated[List[FileChange], Field(description="List of file changes to apply")]
    fix_result: Annotated[Optional[FixResult], Field(description="Result of applying the fix")]
    retry_count: Annotated[int, Field(description="Number of fix attempts made")]
    last_verify_response: Annotated[Optional[OracleResult], Field(description="The last oracle verification result")]
    events: Annotated[List[AgentEvent], Field(description="List of events recorded during agent execution")]

